version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "00:00"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - "astro"
          - "astro-*"
          - "@astrojs/*"
        exclude-patterns:
          - "astro-purgecss"
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint"
          - "eslint-*"
      postcss:
        patterns:
          - "postcss*"
          - "cssnano"
      typescript:
        patterns:
          - "typescript"
          - "typescript-eslint"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
      time: "04:00"
    versioning-strategy: increase
    open-pull-requests-limit: 5
