[project]
name = "photos-reupen-uk"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.7.1",
]

[tool.ruff.lint]
extend-select = ["B0", "I", "PT", "RUF", "SIM", "UP"]
extend-ignore = ["RUF001", "RUF002", "RUF003"]

[tool.ruff.lint.isort]
split-on-trailing-comma=false
